version: '3.9'
services:
  api:
    container_name: iris_fastapi
    volumes:
      - ./app:/app
    build: .
    tty: True
    restart: always
    ports:
      - "8000:8000"
    command: uvicorn main:app --host 0.0.0.0 --port 8000
